r=int(input('shoae ostovaneh: '))
h=int(input('ertefae ostovaneh:'))
pi=3.14
masashatkol=((2*pi*r*h)+(2*pi*r*r))
masahatjanebi=(2*pi*r*h)
hajm=(pi*r*r*h)
print("masahatkil=")
print(masahatkol)
print("masahatjanebi=")
print(masahatjanebi)
print("hajm=")
print(hajm)
